"""Add initial tables

Revision ID: 148c4ef3c7e3
Revises: f4d088ae2ca8
Create Date: 2023-12-28 22:32:50.528904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148c4ef3c7e3'
down_revision: Union[str, None] = 'f4d088ae2ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
