"""add new column

Revision ID: b0af2e359d3c
Revises: 0a87b233c3b5
Create Date: 2024-01-31 00:27:07.250281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0af2e359d3c'
down_revision: Union[str, None] = '0a87b233c3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_sets', sa.Column('foods_id', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.create_index(op.f('ix_food_sets_foods_id'), 'food_sets', ['foods_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_sets_foods_id'), table_name='food_sets')
    op.drop_column('food_sets', 'foods_id')
    # ### end Alembic commands ###
