"""Add initial tables

Revision ID: d52165739b87
Revises: b1bd8c6b78fc
Create Date: 2023-12-30 14:40:02.838366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52165739b87'
down_revision: Union[str, None] = 'b1bd8c6b78fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('employees', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_employees_id', table_name='employees')
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.drop_constraint('employees_employee_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    op.drop_column('employees', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_employee_id_fkey', 'employees', 'users', ['employee_id'], ['id'])
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.create_index('ix_employees_id', 'employees', ['id'], unique=False)
    op.alter_column('employees', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
